### ISSUE TITLE
Error 500 on PrestaShop v1.7.5.2

### ISSUE THREAD

**Issue by SaintMattheus** [wuunder/wuunder-webshopplugin-prestashop#20]
On the newest version of PS version 1.7.5.2, I found out that when you install the Github version in the module-folder you will get an Error 500 when you try to enter the Module Manager. Have tried 3 different ways to get the Wuunder PS Module to install, sadly all times I got the same error over and over.

Maybe there is a coding difference between 1.7 versions. Which has broken the app in version 1.7.5.2? A programmer would find this out in no time at all, but, for me, that has been a long time ago. So, I can't find the code that makes the error.

**Comment by Mittows** [comment]
Hello SainMattheus,

Thanks for your issue submission. 
Going by the information you provided I was not able to reproduce the issue.
I installed release 1.3 of the wuunder-webshopplugin-prestashop on prestashop webshop version 1.7.5.2 and I can enter the Module Manager page without issue.
Could you please describe in detail which steps you have taken while installing the plugin?
Could it be a different plugin causing the error?

**Comment by SaintMattheus** [comment]
Hi @Mittows,

See the attached warning I get. I've downloaded the zip file from the master branch unpacked it made sure this was uploaded to the module folder of the Prestashop installation folder.
Still, we get an Error 500 after upload, and only at the Module Manager page, all other pages are unimpacted by this upload.

![Screen Shot 2019-05-09 at 13 11 33](https://user-images.githubusercontent.com/44919587/57449553-85459b80-725c-11e9-8c64-9c03a278958b.png)
![Screen Shot 2019-05-09 at 13 11 11](https://user-images.githubusercontent.com/44919587/57449554-85459b80-725c-11e9-8eed-f52218f809aa.png)

It's a completely clean installation at this point, only the Dutch language pack has been installed.

**Comment by SaintMattheus** [comment]
And @Mittows, as you probably can see, I'm an idiot :/
Did use the wrong release :)

However, I do not get the shipping module into view on the Module Manager
![Screen Shot 2019-05-09 at 13 23 01](https://user-images.githubusercontent.com/44919587/57450020-a490f880-725d-11e9-8478-ec08766763a9.png)

**Comment by SaintMattheus** [comment]
After recompress it and upload the file through the installer of Prestashop itself it resolved.

**Comment by Mittows** [comment]
Good to hear! Thanks for using our plugin.
